// js/wc2026_fixtures.js
// Static database of all 104 World Cup 2026 matches
// Generated automatically from raw GitHub repository data

const WC2026_FIXTURES = [
  {
    "match_id": "1",
    "home_team": "Mexico",
    "away_team": "South Africa",
    "kickoff_time": "2026-06-11T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "2",
    "home_team": "South Korea",
    "away_team": "Czech Republic",
    "kickoff_time": "2026-06-12T02:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "3",
    "home_team": "Canada",
    "away_team": "Bosnia and Herzegovina",
    "kickoff_time": "2026-06-12T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "4",
    "home_team": "United States",
    "away_team": "Paraguay",
    "kickoff_time": "2026-06-13T01:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "5",
    "home_team": "Haiti",
    "away_team": "Scotland",
    "kickoff_time": "2026-06-14T01:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "6",
    "home_team": "Australia",
    "away_team": "Turkey",
    "kickoff_time": "2026-06-14T04:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "7",
    "home_team": "Brazil",
    "away_team": "Morocco",
    "kickoff_time": "2026-06-13T22:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "8",
    "home_team": "Qatar",
    "away_team": "Switzerland",
    "kickoff_time": "2026-06-13T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "9",
    "home_team": "Ivory Coast",
    "away_team": "Ecuador",
    "kickoff_time": "2026-06-14T23:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "10",
    "home_team": "Germany",
    "away_team": "Curaçao",
    "kickoff_time": "2026-06-14T17:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "11",
    "home_team": "Netherlands",
    "away_team": "Japan",
    "kickoff_time": "2026-06-14T20:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "12",
    "home_team": "Sweden",
    "away_team": "Tunisia",
    "kickoff_time": "2026-06-15T02:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "13",
    "home_team": "Iran",
    "away_team": "New Zealand",
    "kickoff_time": "2026-06-16T01:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "14",
    "home_team": "Spain",
    "away_team": "Cape Verde",
    "kickoff_time": "2026-06-15T16:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "15",
    "home_team": "Belgium",
    "away_team": "Egypt",
    "kickoff_time": "2026-06-15T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "16",
    "home_team": "Saudi Arabia",
    "away_team": "Uruguay",
    "kickoff_time": "2026-06-15T22:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "17",
    "home_team": "France",
    "away_team": "Senegal",
    "kickoff_time": "2026-06-16T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "18",
    "home_team": "Iraq",
    "away_team": "Norway",
    "kickoff_time": "2026-06-16T22:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "19",
    "home_team": "Argentina",
    "away_team": "Algeria",
    "kickoff_time": "2026-06-17T01:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "20",
    "home_team": "Austria",
    "away_team": "Jordan",
    "kickoff_time": "2026-06-17T04:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "21",
    "home_team": "Portugal",
    "away_team": "Democratic Republic of the Congo",
    "kickoff_time": "2026-06-17T17:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "22",
    "home_team": "England",
    "away_team": "Croatia",
    "kickoff_time": "2026-06-17T20:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "23",
    "home_team": "Uzbekistan",
    "away_team": "Colombia",
    "kickoff_time": "2026-06-18T02:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "24",
    "home_team": "Ghana",
    "away_team": "Panama",
    "kickoff_time": "2026-06-17T23:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "25",
    "home_team": "Mexico",
    "away_team": "South Korea",
    "kickoff_time": "2026-06-19T01:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "26",
    "home_team": "Switzerland",
    "away_team": "Bosnia and Herzegovina",
    "kickoff_time": "2026-06-18T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "27",
    "home_team": "Canada",
    "away_team": "Qatar",
    "kickoff_time": "2026-06-18T22:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "28",
    "home_team": "Czech Republic",
    "away_team": "South Africa",
    "kickoff_time": "2026-06-18T16:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "29",
    "home_team": "Brazil",
    "away_team": "Haiti",
    "kickoff_time": "2026-06-20T01:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "30",
    "home_team": "Scotland",
    "away_team": "Morocco",
    "kickoff_time": "2026-06-19T22:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "31",
    "home_team": "United States",
    "away_team": "Australia",
    "kickoff_time": "2026-06-19T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "32",
    "home_team": "Turkey",
    "away_team": "Paraguay",
    "kickoff_time": "2026-06-20T03:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "33",
    "home_team": "Germany",
    "away_team": "Ivory Coast",
    "kickoff_time": "2026-06-20T20:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "34",
    "home_team": "Ecuador",
    "away_team": "Curaçao",
    "kickoff_time": "2026-06-21T00:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "35",
    "home_team": "Netherlands",
    "away_team": "Sweden",
    "kickoff_time": "2026-06-20T17:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "36",
    "home_team": "Tunisia",
    "away_team": "Japan",
    "kickoff_time": "2026-06-21T04:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "37",
    "home_team": "Belgium",
    "away_team": "Iran",
    "kickoff_time": "2026-06-21T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "38",
    "home_team": "New Zealand",
    "away_team": "Egypt",
    "kickoff_time": "2026-06-22T01:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "39",
    "home_team": "Spain",
    "away_team": "Saudi Arabia",
    "kickoff_time": "2026-06-21T16:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "40",
    "home_team": "Uruguay",
    "away_team": "Cape Verde",
    "kickoff_time": "2026-06-21T22:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "41",
    "home_team": "France",
    "away_team": "Iraq",
    "kickoff_time": "2026-06-22T21:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "42",
    "home_team": "Norway",
    "away_team": "Senegal",
    "kickoff_time": "2026-06-23T00:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "43",
    "home_team": "Argentina",
    "away_team": "Austria",
    "kickoff_time": "2026-06-22T17:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "44",
    "home_team": "Jordan",
    "away_team": "Algeria",
    "kickoff_time": "2026-06-23T03:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "45",
    "home_team": "Portugal",
    "away_team": "Uzbekistan",
    "kickoff_time": "2026-06-23T17:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "46",
    "home_team": "Panama",
    "away_team": "Croatia",
    "kickoff_time": "2026-06-23T23:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "47",
    "home_team": "Colombia",
    "away_team": "Democratic Republic of the Congo",
    "kickoff_time": "2026-06-24T02:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "48",
    "home_team": "England",
    "away_team": "Ghana",
    "kickoff_time": "2026-06-23T20:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "49",
    "home_team": "Scotland",
    "away_team": "Brazil",
    "kickoff_time": "2026-06-24T22:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "50",
    "home_team": "Morocco",
    "away_team": "Haiti",
    "kickoff_time": "2026-06-24T22:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "51",
    "home_team": "South Africa",
    "away_team": "South Korea",
    "kickoff_time": "2026-06-25T01:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "52",
    "home_team": "Czech Republic",
    "away_team": "Mexico",
    "kickoff_time": "2026-06-25T01:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "53",
    "home_team": "Bosnia and Herzegovina",
    "away_team": "Qatar",
    "kickoff_time": "2026-06-24T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "54",
    "home_team": "Switzerland",
    "away_team": "Canada",
    "kickoff_time": "2026-06-24T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "55",
    "home_team": "Curaçao",
    "away_team": "Ivory Coast",
    "kickoff_time": "2026-06-25T20:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "56",
    "home_team": "Ecuador",
    "away_team": "Germany",
    "kickoff_time": "2026-06-25T20:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "57",
    "home_team": "Paraguay",
    "away_team": "Australia",
    "kickoff_time": "2026-06-26T02:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "58",
    "home_team": "Turkey",
    "away_team": "United States",
    "kickoff_time": "2026-06-26T02:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "59",
    "home_team": "Japan",
    "away_team": "Sweden",
    "kickoff_time": "2026-06-25T23:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "60",
    "home_team": "Tunisia",
    "away_team": "Netherlands",
    "kickoff_time": "2026-06-25T23:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "61",
    "home_team": "Senegal",
    "away_team": "Iraq",
    "kickoff_time": "2026-06-26T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "62",
    "home_team": "Norway",
    "away_team": "France",
    "kickoff_time": "2026-06-26T19:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "63",
    "home_team": "Egypt",
    "away_team": "Iran",
    "kickoff_time": "2026-06-27T03:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "64",
    "home_team": "New Zealand",
    "away_team": "Belgium",
    "kickoff_time": "2026-06-27T03:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "65",
    "home_team": "Cape Verde",
    "away_team": "Saudi Arabia",
    "kickoff_time": "2026-06-27T00:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "66",
    "home_team": "Uruguay",
    "away_team": "Spain",
    "kickoff_time": "2026-06-27T00:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "67",
    "home_team": "Panama",
    "away_team": "England",
    "kickoff_time": "2026-06-27T21:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "68",
    "home_team": "Croatia",
    "away_team": "Ghana",
    "kickoff_time": "2026-06-27T21:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "69",
    "home_team": "Algeria",
    "away_team": "Austria",
    "kickoff_time": "2026-06-28T02:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "70",
    "home_team": "Jordan",
    "away_team": "Argentina",
    "kickoff_time": "2026-06-28T02:00:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "71",
    "home_team": "Colombia",
    "away_team": "Portugal",
    "kickoff_time": "2026-06-27T23:30:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "72",
    "home_team": "Democratic Republic of the Congo",
    "away_team": "Uzbekistan",
    "kickoff_time": "2026-06-27T23:30:00.000Z",
    "phase": "GROUP",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "73",
    "home_team": "Runner-up Group A",
    "away_team": "Runner-up Group B",
    "kickoff_time": "2026-06-28T19:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "74",
    "home_team": "Winner Group E",
    "away_team": "3rd Group A/B/C/D/F",
    "kickoff_time": "2026-06-29T20:30:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "75",
    "home_team": "Winner Group F",
    "away_team": "Runner-up Group C",
    "kickoff_time": "2026-06-30T01:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "76",
    "home_team": "Winner Group C",
    "away_team": "Runner-up Group F",
    "kickoff_time": "2026-06-29T17:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "77",
    "home_team": "Winner Group I",
    "away_team": "3rd Group C/D/F/G/H",
    "kickoff_time": "2026-06-30T21:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "78",
    "home_team": "Runner-up Group E",
    "away_team": "Runner-up Group I",
    "kickoff_time": "2026-06-30T17:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "79",
    "home_team": "Winner Group A",
    "away_team": "3rd Group C/E/F/H/I",
    "kickoff_time": "2026-07-01T01:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "80",
    "home_team": "Winner Group L",
    "away_team": "3rd Group E/H/I/J/K",
    "kickoff_time": "2026-07-01T16:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "81",
    "home_team": "Winner Group D",
    "away_team": "3rd Group B/E/F/I/J",
    "kickoff_time": "2026-07-02T00:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "82",
    "home_team": "Winner Group G",
    "away_team": "3rd Group A/E/H/I/J",
    "kickoff_time": "2026-07-01T20:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "83",
    "home_team": "Runner-up Group K",
    "away_team": "Runner-up Group L",
    "kickoff_time": "2026-07-02T23:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "84",
    "home_team": "Winner Group H",
    "away_team": "Runner-up Group J",
    "kickoff_time": "2026-07-02T19:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "85",
    "home_team": "Winner Group B",
    "away_team": "3rd Group E/F/G/I/J",
    "kickoff_time": "2026-07-03T03:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "86",
    "home_team": "Winner Group J",
    "away_team": "Runner-up Group H",
    "kickoff_time": "2026-07-03T22:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "87",
    "home_team": "Winner Group K",
    "away_team": "3rd Group D/E/I/J/L",
    "kickoff_time": "2026-07-04T01:30:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "88",
    "home_team": "Runner-up Group D",
    "away_team": "Runner-up Group G",
    "kickoff_time": "2026-07-03T18:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "89",
    "home_team": "Winner Match 74",
    "away_team": "Winner Match 77",
    "kickoff_time": "2026-07-04T21:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "90",
    "home_team": "Winner Match 73",
    "away_team": "Winner Match 75",
    "kickoff_time": "2026-07-04T17:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "91",
    "home_team": "Winner Match 76",
    "away_team": "Winner Match 78",
    "kickoff_time": "2026-07-05T20:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "92",
    "home_team": "Winner Match 79",
    "away_team": "Winner Match 80",
    "kickoff_time": "2026-07-06T00:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "93",
    "home_team": "Winner Match 83",
    "away_team": "Winner Match 84",
    "kickoff_time": "2026-07-06T19:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "94",
    "home_team": "Winner Match 81",
    "away_team": "Winner Match 82",
    "kickoff_time": "2026-07-07T00:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "95",
    "home_team": "Winner Match 86",
    "away_team": "Winner Match 88",
    "kickoff_time": "2026-07-07T16:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "96",
    "home_team": "Winner Match 85",
    "away_team": "Winner Match 87",
    "kickoff_time": "2026-07-07T20:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "97",
    "home_team": "Winner Match 89",
    "away_team": "Winner Match 90",
    "kickoff_time": "2026-07-09T20:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "98",
    "home_team": "Winner Match 93",
    "away_team": "Winner Match 94",
    "kickoff_time": "2026-07-10T19:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "99",
    "home_team": "Winner Match 91",
    "away_team": "Winner Match 92",
    "kickoff_time": "2026-07-11T21:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "100",
    "home_team": "Winner Match 95",
    "away_team": "Winner Match 96",
    "kickoff_time": "2026-07-12T01:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "101",
    "home_team": "Winner Match 97",
    "away_team": "Winner Match 98",
    "kickoff_time": "2026-07-14T19:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "102",
    "home_team": "Winner Match 99",
    "away_team": "Winner Match 100",
    "kickoff_time": "2026-07-15T19:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "103",
    "home_team": "Loser Match 101",
    "away_team": "Loser Match 102",
    "kickoff_time": "2026-07-18T21:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  },
  {
    "match_id": "104",
    "home_team": "Winner Match 101",
    "away_team": "Winner Match 102",
    "kickoff_time": "2026-07-19T19:00:00.000Z",
    "phase": "KNOCKOUT",
    "competition": "WC",
    "status": "SCHEDULED",
    "result": "",
    "home_score": "",
    "away_score": ""
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { WC2026_FIXTURES };
}
